# Generated by Django 5.1.1 on 2026-04-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('game_type', models.CharField(choices=[('spin', 'Spin Wheel'), ('scratch', 'Scratch'), ('quiz', 'Quiz')], default='spin', max_length=20)),
                ('reward_label', models.CharField(default='-10% sur votre prochaine visite', max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('channel', models.CharField(choices=[('qr', 'QR Code'), ('nfc', 'NFC'), ('hybrid', 'QR + NFC')], default='qr', max_length=20)),
                ('placement', models.CharField(default='counter', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='campaigns.campaign')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='merchants.merchant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
