# Generated by Django 5.1.1 on 2026-04-20 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('probability_weight', models.PositiveIntegerField(default=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('daily_quota', models.PositiveIntegerField(default=100)),
                ('color', models.CharField(default='#f59e0b', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_segments', to='campaigns.campaign')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wheel_segments', to='rewards.reward')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
