# Generated by Django 5.1.1 on 2026-04-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_journey_type_campaign_wallet_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='journey_type',
            field=models.CharField(choices=[('premium_mobile', 'Mobile premium'), ('growly_reference', 'Growly référence'), ('compact', 'Compact')], default='premium_mobile', max_length=40),
        ),
    ]
