# Generated by Django 5.1.1 on 2026-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_journey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='journey_type',
            field=models.CharField(choices=[('premium_mobile', 'Mobile premium'), ('growly_reference', 'Growly référence'), ('street_food', 'Street food / Kebab'), ('trattoria', 'Restaurant italien'), ('padel_arena', 'Sport / Padel'), ('compact', 'Compact')], default='premium_mobile', max_length=40),
        ),
    ]
