# Generated by Django 5.1.1 on 2026-04-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_alter_campaign_journey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='quiz_answer_a',
            field=models.CharField(default='Un café offert', max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='quiz_answer_b',
            field=models.CharField(default='Un dessert maison', max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='quiz_answer_c',
            field=models.CharField(default='-10% sur l’addition', max_length=120),
        ),
        migrations.AddField(
            model_name='campaign',
            name='quiz_question',
            field=models.CharField(default='Quelle offre préférez-vous aujourd’hui ?', max_length=220),
        ),
        migrations.AddField(
            model_name='campaign',
            name='scratch_label',
            field=models.CharField(default='Grattez ici', max_length=120),
        ),
    ]
