# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaign_quiz_answer_a_campaign_quiz_answer_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrypoint',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
