# Generated by Django 5.1.1 on 2026-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_entrypoint_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypoint',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
