# Generated by Django 5.1.1 on 2026-05-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_entrypoint_redirect_url'),
        ('merchants', '0012_remove_merchant_employee_pin_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['merchant', 'created_at'], name='campaigns_c_merchan_a69b0f_idx'),
        ),
    ]
