# Generated by Django 5.1.1 on 2026-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_gamesession_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='claim_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
