# Generated by Django 5.1.1 on 2026-04-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_journey_type'),
        ('customers', '0003_customer_consent_marketing_gamesession_claim_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'Apple Wallet'), ('google', 'Google Wallet')], max_length=20)),
                ('serial_number', models.CharField(max_length=80)),
                ('auth_token', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ready', 'Prêt'), ('issued', 'Émis'), ('revoked', 'Révoqué'), ('error', 'Erreur')], default='draft', max_length=20)),
                ('pass_url', models.URLField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_passes', to='campaigns.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_passes', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'serial_number')},
            },
        ),
    ]
