# Generated by Django 5.1.1 on 2026-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_walletpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletpass',
            name='scan_code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='walletpass',
            name='stamps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='walletpass',
            name='stamps_target',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
