# Generated by Django 5.1.1 on 2026-05-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_gamesession_claim_link_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_marketing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
