# Generated by Django 5.1.1 on 2026-05-16 19:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customer_deleted_at_customer_deleted_by'),
        ('merchants', '0012_remove_merchant_employee_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=80)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='customers.customer')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='customers.gamesession')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_jobs', to='merchants.merchant')),
            ],
            options={
                'ordering': ['scheduled_at', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='customers_n_status_095ad3_idx'), models.Index(fields=['channel'], name='customers_n_channel_24f99e_idx'), models.Index(fields=['provider'], name='customers_n_provide_6289f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('game_session', 'channel'), name='uniq_notification_job_session_channel')],
            },
        ),
    ]
