# Generated by Django 5.1.1 on 2026-05-16 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_campaigns_c_merchan_a69b0f_idx'),
        ('customers', '0009_notificationjob'),
        ('merchants', '0012_remove_merchant_employee_pin_and_more'),
        ('rewards', '0002_french_reward_type_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['merchant', 'deleted_at', 'created_at'], name='customers_c_merchan_4d2271_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['customer', 'created_at'], name='customers_g_custome_81ed2f_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['campaign', 'created_at'], name='customers_g_campaig_7e7ff2_idx'),
        ),
    ]
