# Generated by Django 5.1.1 on 2026-05-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('merchants', '0012_remove_merchant_employee_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scans_count', models.PositiveIntegerField(default=0)),
                ('contacts_count', models.PositiveIntegerField(default=0)),
                ('winners_count', models.PositiveIntegerField(default=0)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('review_clicks_count', models.PositiveIntegerField(default=0)),
                ('wallet_passes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-date', 'merchant__name'],
                'indexes': [models.Index(fields=['merchant'], name='core_mercha_merchan_3e6ce6_idx'), models.Index(fields=['date'], name='core_mercha_date_a788cc_idx'), models.Index(fields=['merchant', 'date'], name='core_mercha_merchan_fb5860_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'date'), name='uniq_merchant_daily_metric_date')],
            },
        ),
    ]
