# Generated by Django 5.1.1 on 2026-04-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('reward_type', models.CharField(choices=[('discount', 'Discount'), ('gift', 'Gift'), ('free_item', 'Free item'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('description', models.CharField(max_length=180)),
                ('probability_weight', models.PositiveIntegerField(default=100)),
                ('daily_quota', models.PositiveIntegerField(default=100)),
                ('total_distributed', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('expires_in_hours', models.PositiveIntegerField(default=168)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='campaigns.campaign')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='merchants.merchant')),
            ],
            options={
                'ordering': ['merchant__name', 'name'],
            },
        ),
    ]
