# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('discount', 'Réduction'), ('gift', 'Cadeau'), ('free_item', 'Produit offert'), ('custom', 'Offre personnalisée')], default='custom', max_length=20),
        ),
    ]
