# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_merchant_body_font_merchant_heading_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='google_review_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
