# Generated by Django 5.1.1 on 2026-05-16 16:34

import apps.merchants.models
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def migrate_employee_pin_to_hash(apps, schema_editor):
    Merchant = apps.get_model('merchants', 'Merchant')
    for merchant in Merchant.objects.all().only('id', 'employee_pin'):
        raw_pin = (merchant.employee_pin or '').strip() or '123456'
        Merchant.objects.filter(pk=merchant.pk).update(employee_pin_hash=make_password(raw_pin))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_merchant_deleted_at_merchant_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='employee_pin_hash',
            field=models.CharField(default=apps.merchants.models.default_employee_pin_hash, max_length=128),
        ),
        migrations.RunPython(migrate_employee_pin_to_hash, noop_reverse),
        migrations.RemoveField(
            model_name='merchant',
            name='employee_pin',
        ),
    ]
