# Generated by OpenClaw

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_remove_merchant_employee_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='public_journey_tested',
            field=models.BooleanField(default=False),
        ),
    ]
