from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from apps.core.views import (
    admin_dashboard,
    analytics_view,
    automations_view,
    customer_detail,
    customers_export_csv,
    customers_list,
    delete_customer,
    game_configuration,
    home,
    login_view,
    logout_view,
    merchant_onboarding,
    merchant_setup,
    play_page,
    qr_preview,
    redeem_session,
    reward_delete,
    rewards_list,
    review_configuration,
    toggle_campaign_flag,
    wallet_configuration,
    wallet_pass_scan,
    apple_wallet_pass,
    google_wallet_pass,
)

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', home, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('admin/', admin_dashboard, name='admin-dashboard'),
    path('admin/onboarding/', merchant_onboarding, name='merchant-onboarding'),
    path('admin/game/', game_configuration, name='game-configuration'),
    path('admin/game/review/', review_configuration, name='review-configuration'),
    path('admin/game/wallet/', wallet_configuration, name='wallet-configuration'),
    path('admin/wallet/scan/<str:scan_code>/', wallet_pass_scan, name='wallet-pass-scan'),
    path('admin/campaign/toggle/', toggle_campaign_flag, name='toggle-campaign-flag'),
    path('admin/setup/', merchant_setup, name='merchant-setup'),
    path('admin/customers/', customers_list, name='customers-list'),
    path('admin/customers/export/', customers_export_csv, name='customers-export-csv'),
    path('admin/customers/<int:customer_id>/', customer_detail, name='customer-detail'),
    path('admin/customers/<int:customer_id>/delete/', delete_customer, name='customer-delete'),
    path('admin/rewards/', rewards_list, name='rewards-list'),
    path('admin/rewards/<int:reward_id>/delete/', reward_delete, name='reward-delete'),
    path('admin/analytics/', analytics_view, name='analytics-view'),
    path('admin/automations/', automations_view, name='automations-view'),
    path('admin/sessions/<int:session_id>/redeem/', redeem_session, name='redeem-session'),
    path('admin/qr/<str:code>.svg', qr_preview, name='qr-preview'),
    path('play/<slug:slug>/', play_page, name='play-page'),
    path('play/<slug:slug>/wallet/apple/', apple_wallet_pass, name='apple-wallet-pass'),
    path('play/<slug:slug>/wallet/google/', google_wallet_pass, name='google-wallet-pass'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
